version: '3.1'

services:
  database:
    image: postgres:11.4-alpine
    container_name: trailblazer-postgres
    environment:
      POSTGRES_USER: trailblazer
      POSTGRES_PASSWORD: jFJzZ@9d&aHFpzPkM9xk8tTsU4ZKrTaP
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
